### PR TITLE
Project cleanup, various fixes, enhance the server sync feature

### PR DESCRIPTION
**Pull request by sgdc3**

### CODE REVIEW

**Comment by AppleDash** [comment]
Thank you very much for your work. I'll review it tonight.

**Comment by AppleDash** [comment]
I can't take it as it is, but I've gone through the first commit and added the parts I enjoy. What does the second commit re: custom number locale do, exactly? Will this fix the 1000$ reset bug?

**Comment by sgdc3** [comment]
I hope it does xD

**Comment by sgdc3** [comment]
>I can't take it as it is

why?
I spent hours clening up the maven structure to make it clean, also you missed the section sync feature, that makes this plugin nice for large networks.

**Comment by AppleDash** [comment]
Because I like it how it is - I never asked anyone to do that & all it does is make it harder for me to understand while adding no functionality improvement.

I don't know what feature I missed - I am still waiting for an explanation for the second commit before I look too hard at it.

**Comment by AppleDash** [comment]
Also, your PR introduces an SQL injection vulnerability.

**Comment by sgdc3** [comment]
@AppleDash i know, i forgot to add the prepared statement variable

**Pull request closed without merging**
